/// Flutter icons FoodrIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FoodrIcons
///      fonts:
///       - asset: fonts/FoodrIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FoodrIcons {
  FoodrIcons._();

  static const _kFontFam = 'FoodrIcons';
  static const String? _kFontPkg = null;

  static const IconData bag = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag_inactive = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeinactive = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orders = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orders_inactive = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile_inactive = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
